<?php

namespace Database\Seeders;

use App\Models\ServiceCategory;
use App\Models\Service;
use Illuminate\Database\Seeder;

class ServiceSeeder extends Seeder
{
    public function run(): void
    {
        $categories = ServiceCategory::query()->pluck('id', 'slug');

        $services = [
            [
                'name' => 'Backend Laravel',
                'code' => 'BACKEND-LARAVEL',
                'description' => 'Implementação de backend em Laravel.',
                'service_category_id' => $categories['programacao-php'] ?? null,
                'category' => 'Programação PHP',
                'type' => 'hourly',
                'unit_type' => 'hora',
                'default_price' => 90.00,
                'is_active' => true,
            ],
            [
                'name' => 'Sistema Laravel',
                'code' => 'SISTEMA-LARAVEL',
                'description' => 'Desenvolvimento de sistemas em Laravel.',
                'service_category_id' => $categories['programacao-php'] ?? null,
                'category' => 'Programação PHP',
                'type' => 'hourly',
                'unit_type' => 'hora',
                'default_price' => 90.00,
                'is_active' => true,
            ],
            [
                'name' => 'API Laravel',
                'code' => 'API-LARAVEL',
                'description' => 'Criação e manutenção de APIs em Laravel.',
                'service_category_id' => $categories['programacao-php'] ?? null,
                'category' => 'Programação PHP',
                'type' => 'hourly',
                'unit_type' => 'hora',
                'default_price' => 90.00,
                'is_active' => true,
            ],
            [
                'name' => 'Backend Go',
                'code' => 'BACKEND-GO',
                'description' => 'Implementação de backend em Go.',
                'service_category_id' => $categories['programacao-go'] ?? null,
                'category' => 'Programação Go',
                'type' => 'hourly',
                'unit_type' => 'hora',
                'default_price' => 120.00,
                'is_active' => true,
            ],
            [
                'name' => 'API Go',
                'code' => 'API-GO',
                'description' => 'Criação de APIs com Go.',
                'service_category_id' => $categories['programacao-go'] ?? null,
                'category' => 'Programação Go',
                'type' => 'hourly',
                'unit_type' => 'hora',
                'default_price' => 120.00,
                'is_active' => true,
            ],
            [
                'name' => 'Microsserviço Go',
                'code' => 'MICROSERVICO-GO',
                'description' => 'Desenvolvimento de microsserviços com Go.',
                'service_category_id' => $categories['programacao-go'] ?? null,
                'category' => 'Programação Go',
                'type' => 'hourly',
                'unit_type' => 'hora',
                'default_price' => 120.00,
                'is_active' => true,
            ],
            [
                'name' => 'Backend Node',
                'code' => 'BACKEND-NODE',
                'description' => 'Implementação de backend com Node.',
                'service_category_id' => $categories['programacao-nodejs'] ?? null,
                'category' => 'Programação NodeJS',
                'type' => 'hourly',
                'unit_type' => 'hora',
                'default_price' => 100.00,
                'is_active' => true,
            ],
            [
                'name' => 'API Node',
                'code' => 'API-NODE',
                'description' => 'Criação de APIs com Node.',
                'service_category_id' => $categories['programacao-nodejs'] ?? null,
                'category' => 'Programação NodeJS',
                'type' => 'hourly',
                'unit_type' => 'hora',
                'default_price' => 100.00,
                'is_active' => true,
            ],
            [
                'name' => 'Microsserviço Node',
                'code' => 'MICROSERVICO-NODE',
                'description' => 'Desenvolvimento de microsserviços com Node.',
                'service_category_id' => $categories['programacao-nodejs'] ?? null,
                'category' => 'Programação NodeJS',
                'type' => 'hourly',
                'unit_type' => 'hora',
                'default_price' => 100.00,
                'is_active' => true,
            ],
            [
                'name' => 'Criação de layout',
                'code' => 'CRIACAO-LAYOUT',
                'description' => 'Design de layout para websites e sistemas.',
                'service_category_id' => $categories['web-design'] ?? null,
                'category' => 'Web Design',
                'type' => 'hourly',
                'unit_type' => 'hora',
                'default_price' => 120.00,
                'is_active' => true,
            ],
            [
                'name' => 'Desenvolvimento Frontend Vue',
                'code' => 'FRONTEND-VUE',
                'description' => 'Desenvolvimento frontend com Vue.',
                'service_category_id' => $categories['programacao-jsts'] ?? null,
                'category' => 'Programação JS/TS',
                'type' => 'hourly',
                'unit_type' => 'hora',
                'default_price' => 90.00,
                'is_active' => true,
            ],
            [
                'name' => 'Desenvolvimento Frontend React',
                'code' => 'FRONTEND-REACT',
                'description' => 'Desenvolvimento frontend com React.',
                'service_category_id' => $categories['programacao-jsxtsx'] ?? null,
                'category' => 'Programação JSX/TSX',
                'type' => 'hourly',
                'unit_type' => 'hora',
                'default_price' => 90.00,
                'is_active' => true,
            ],
            [
                'name' => 'Planejamento de sistema',
                'code' => 'PLANEJAMENTO-SISTEMA',
                'description' => 'Planejamento técnico e funcional do sistema.',
                'service_category_id' => $categories['arquitetura-software'] ?? null,
                'category' => 'Arquitetura de Software',
                'type' => 'hourly',
                'unit_type' => 'hora',
                'default_price' => 250.00,
                'is_active' => true,
            ],
            [
                'name' => 'Estruturação de sistema',
                'code' => 'ESTRUTURACAO-SISTEMA',
                'description' => 'Estruturação arquitetural e técnica do sistema.',
                'service_category_id' => $categories['engenharia-software'] ?? null,
                'category' => 'Engenharia de Software',
                'type' => 'hourly',
                'unit_type' => 'hora',
                'default_price' => 250.00,
                'is_active' => true,
            ],
            [
                'name' => 'Configuração de Infraestrutura',
                'code' => 'CONFIG-INFRA',
                'description' => 'Configuração e manutenção de infraestrutura cloud.',
                'service_category_id' => $categories['cloud-engineering'] ?? null,
                'category' => 'Cloud Engineering',
                'type' => 'hourly',
                'unit_type' => 'hora',
                'default_price' => 100.00,
                'is_active' => true,
            ],
            [
                'name' => 'Refatoração de Código PHP',
                'code' => 'REFATORACAO-PHP',
                'description' => 'Refatoração de código em PHP.',
                'service_category_id' => $categories['programacao-php'] ?? null,
                'category' => 'Programação PHP',
                'type' => 'hourly',
                'unit_type' => 'hora',
                'default_price' => 90.00,
                'is_active' => true,
            ],
            [
                'name' => 'Refatoração de Código GO',
                'code' => 'REFATORACAO-GO',
                'description' => 'Refatoração de código em Go.',
                'service_category_id' => $categories['programacao-go'] ?? null,
                'category' => 'Programação Go',
                'type' => 'hourly',
                'unit_type' => 'hora',
                'default_price' => 120.00,
                'is_active' => true,
            ],
            [
                'name' => 'Refatoração de Código Node',
                'code' => 'REFATORACAO-NODE',
                'description' => 'Refatoração de código em Node.',
                'service_category_id' => $categories['programacao-nodejs'] ?? null,
                'category' => 'Programação NodeJS',
                'type' => 'hourly',
                'unit_type' => 'hora',
                'default_price' => 90.00,
                'is_active' => true,
            ],
            [
                'name' => 'Desenvolvimento de Tema Wordpress',
                'code' => 'TEMA-WORDPRESS',
                'description' => 'Desenvolvimento de temas para Wordpress.',
                'service_category_id' => $categories['programacao-php'] ?? null,
                'category' => 'Programação PHP',
                'type' => 'hourly',
                'unit_type' => 'hora',
                'default_price' => 90.00,
                'is_active' => true,
            ],
            [
                'name' => 'Desenvolvimento de Plugin Wordpress',
                'code' => 'PLUGIN-WORDPRESS',
                'description' => 'Desenvolvimento de plugins para Wordpress.',
                'service_category_id' => $categories['programacao-php'] ?? null,
                'category' => 'Programação PHP',
                'type' => 'hourly',
                'unit_type' => 'hora',
                'default_price' => 90.00,
                'is_active' => true,
            ],
        ];

        foreach ($services as $service) {
            Service::updateOrCreate(
                ['code' => $service['code']],
                $service
            );
        }
    }
}
